apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mysql-rs-secret
  labels:
    app: mysql-rs-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-rs-pod
  template:
    metadata:
      labels:
        app: mysql-rs-pod
    spec:
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: claim1
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: mypass
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: database
          mountPath: /var/lib/mysql
